version: '2'
services:
 
  web1:
    environment: 
      - KafkaOptions__Topic=d831j5n3-messages
      - KafkaOptions__BootstrapServers=dory-01.srvs.cloudkafka.com:9094,dory-02.srvs.cloudkafka.com:9094,dory-03.srvs.cloudkafka.com:9094
      - KafkaOptions__Username=d831j5n3
      - KafkaOptions__Password=rjTUZDDbG9Tultmhev5h2MInzi3D8riq
      - KafkaOptions__GroupId=web1
      - ConnectionStrings__db=Server=db;Database=kchat;User Id=sa;Password=P@assW@rd;

  web2:
    environment: 
      - KafkaOptions__Topic=d831j5n3-messages
      - KafkaOptions__BootstrapServers=dory-01.srvs.cloudkafka.com:9094,dory-02.srvs.cloudkafka.com:9094,dory-03.srvs.cloudkafka.com:9094
      - KafkaOptions__Username=d831j5n3
      - KafkaOptions__Password=rjTUZDDbG9Tultmhev5h2MInzi3D8riq
      - KafkaOptions__GroupId=web2
      - ConnectionStrings__db=Server=db;Database=kchat;User Id=sa;Password=P@assW@rd;