using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kchat.UI.Framework
{
    public class LokiService
    {
        public void GenerateMessageException(string text, string value, string desc)
        {
            if (string.Equals(text, value, StringComparison.InvariantCultureIgnoreCase))
            {
                throw new ApplicationException($"(Auto Generated by Loki): {desc}");
            }
        }
    }
}
